#bash!

make

#errors here
echo "--------------------nofile--------"
./cub3D maps/notexist.cub
echo "--------------------1file--------"
./cub3D maps/1file
echo "--------------------2empty.cub--------"
./cub3D maps/2empty.cub
echo "--------------------3color.cub--------"
./cub3D maps/3color.cub
echo "--------------------4color.cub--------"
./cub3D maps/4color.cub
echo "--------------------5res.cub--------"
./cub3D maps/5res.cub
echo "--------------------6res.cub--------"
./cub3D maps/6res.cub
echo "--------------------7tex.cub--------"
./cub3D maps/7tex.cub
echo "--------------------8double.cub--------"
./cub3D maps/8double.cub
echo "--------------------9map.cub--------"
./cub3D maps/9map.cub
echo "--------------------10param.cub--------"
./cub3D maps/10param.cub
echo "--------------------11lines.cub--------"
./cub3D maps/11lines.cub
echo "--------------------12holes.cub--------"
./cub3D maps/12holes.cub
echo "--------------------13player.cub--------"
./cub3D maps/13player.cub
echo "--------------------14player.cub--------"
./cub3D maps/14player.cub
echo "--------------------15param.cub--------"
./cub3D maps/15param.cub
echo "--------------------16closed.cub--------"
./cub3D maps/16closed.cub
echo "--------------------17closed.cub--------"
./cub3D maps/17closed.cub
echo "--------------------18closed.cub--------"
./cub3D maps/18closed.cub
echo "--------------------19closed.cub--------"
./cub3D maps/19closed.cub
echo "--------------------20closed.cub--------"
./cub3D maps/20closed.cub
echo "--------------------21closed.cub--------"
./cub3D maps/21closed.cub

#okay here
echo "--------------------okay1.cub--------"
./cub3D maps/okay1.cub
echo "--------------------okay2.cub--------"
./cub3D maps/okay2.cub
echo "--------------------okay3.cub--------"
./cub3D maps/okay3.cub
echo "--------------------okay4.cub--------"
./cub3D maps/okay4.cub
echo "--------------------okay5.cub--------"
./cub3D maps/okay5.cub
echo "--------------------okay6.cub--------"
./cub3D maps/okay6.cub
echo "--------------------okay7.cub--------"
./cub3D maps/okay7.cub
echo "--------------------okay8.cub--------"
./cub3D maps/okay8.cub
echo "--------------------okay9.cub.cub--------"
./cub3D maps/okay9.cub.cub
echo "--------------------okay10.cub--------"
./cub3D maps/okay10.cub
echo "--------------------okay11.cub--------"
./cub3D maps/okay11.cub
